syntax = "proto3";

package mnist;

service MnistService {
    // Fase 1: Despliegue del modelo
    rpc UploadModel (ModelRequest) returns (ModelResponse);
    // Fase 2: Inferencia de imágenes
    rpc Procesar (BatchRequest) returns (BatchResponse);
}

message ModelRequest {
    bytes model_data = 1; 
}

message ModelResponse {
    string message = 1;
}

message BatchRequest {
    int32 batch_id = 1;
    bytes image_data = 2; 
}

message BatchResponse {
    int32 batch_id = 1;
    repeated int32 predictions = 2; // Ahora devolvemos las predicciones de la IA
    string status = 3;
    float ram_usage = 4;
    float cpu_usage = 5;
    float t_proc_ms = 6;
}