---
# Usuario para la conexión SSH y el Linger
ansible_user: littledragon
# Llave SSH para autenticación
ansible_ssh_private_key_file: ~/.ssh/id_rsa

# Variables del servicio
web_port: 8000

#experimento_path: "../results/http"

#experimento_path: "../results/grpc"

experimento_path: "../results/zeromq"